In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
from keras import Sequential
from keras.layers import Dense , Input
from sklearn.model_selection import train_test_split

#Binary Cls

Data

In [4]:
path_1 = pd.read_csv("titanic_data.csv")

In [5]:
path_1.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [6]:

data = path_1.dropna()
data

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
6,0,1,male,54.0,0,0,51.8625,S,First,man,True,E,Southampton,no,True
10,1,3,female,4.0,1,1,16.7000,S,Third,child,False,G,Southampton,yes,False
11,1,1,female,58.0,0,0,26.5500,S,First,woman,False,C,Southampton,yes,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
869,1,1,female,47.0,1,1,52.5542,S,First,woman,False,D,Southampton,yes,False
870,0,1,male,33.0,0,0,5.0000,S,First,man,True,B,Southampton,no,True
877,1,1,female,56.0,0,1,83.1583,C,First,woman,False,C,Cherbourg,yes,False
885,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
887,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True

In [7]:
x_ = data.drop(columns=['survived','alive'])
x_

,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alone
1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,False
3,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,False
6,1,male,54.0,0,0,51.8625,S,First,man,True,E,Southampton,True
10,3,female,4.0,1,1,16.7000,S,Third,child,False,G,Southampton,False
11,1,female,58.0,0,0,26.5500,S,First,woman,False,C,Southampton,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...
869,1,female,47.0,1,1,52.5542,S,First,woman,False,D,Southampton,False
870,1,male,33.0,0,0,5.0000,S,First,man,True,B,Southampton,True
877,1,female,56.0,0,1,83.1583,C,First,woman,False,C,Cherbourg,False
885,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,True
887,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,True

In [8]:
y_ = data[['survived']]
y_

     survived
1           1
3           1
6           0
10          1
11          1
..        ...
869         1
870         0
877         1
885         1
887         1

[182 rows x 1 columns]

In [10]:

x_encoded = pd.get_dummies(x_)

In [12]:
X_train, X_test, y_train, y_test = train_test_split(x_encoded, y_, test_size=0.2, random_state=42)

In [13]:
model = Sequential()
model.add(Input(shape = (X_train.shape[1],))) # Update input shape based on the number of columns after encoding
model.add(Dense(20, activation='relu'))
model.add(Dense(20, activation='relu'))
model.add(Dense(1, 'sigmoid'))

In [14]:
model.compile(optimizer='adam', loss='mse', metrics=['accuracy'])

In [15]:
model.fit(X_train, y_train, validation_data=(X_test, y_test),epochs=100, batch_size=32)

Epoch 1/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 2s 69ms/step - accuracy: 0.6897 - loss: 0.2343 - val_accuracy: 0.6757 - val_loss: 0.2234
Epoch 2/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.6897 - loss: 0.2008 - val_accuracy: 0.6757 - val_loss: 0.2128
Epoch 3/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.6966 - loss: 0.1966 - val_accuracy: 0.6216 - val_loss: 0.2190
Epoch 4/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.7241 - loss: 0.1951 - val_accuracy: 0.5676 - val_loss: 0.2283
Epoch 5/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.7379 - loss: 0.1895 - val_accuracy: 0.6216 - val_loss: 0.2189
Epoch 6/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.7724 - loss: 0.1839 - val_accuracy: 0.5405 - val_loss: 0.2227
Epoch 7/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.7172 - loss: 0.1818 - val_accuracy: 0.5676 - val_loss: 0.2369
Epoch 8/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.7379 - loss: 0.1806 - val_accuracy: 0.5676 - val_loss: 0.2243
Epoch 9/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.7655 - loss: 0.1722 - val_accuracy: 0.5946 - val_loss: 0.2188
Epoch 10/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.7655 - loss: 0.1689 - val_accuracy: 0.5676 - val_loss: 0.2202
Epoch 11/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.7448 - loss: 0.1690 - val_accuracy: 0.5676 - val_loss: 0.2191
Epoch 12/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.7586 - loss: 0.1641 - val_accuracy: 0.5405 - val_loss: 0.2207
Epoch 13/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.7655 - loss: 0.1602 - val_accuracy: 0.5946 - val_loss: 0.2169
Epoch 14/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.7862 - loss: 0.1589 - val_accuracy: 0.5405 - val_loss: 0.2198
Epoch 15/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.7793 - loss: 0.1558 - val_accuracy: 0.5405 - val_loss: 0.2208
Epoch 16/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.7586 - loss: 0.1600 - val_accuracy: 0.5676 - val_loss: 0.2243
Epoch 17/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.7655 - loss: 0.1614 - val_accuracy: 0.5946 - val_loss: 0.2181
Epoch 18/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.8000 - loss: 0.1533 - val_accuracy: 0.5946 - val_loss: 0.2188
Epoch 19/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.7586 - loss: 0.1547 - val_accuracy: 0.5946 - val_loss: 0.2188
Epoch 20/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.8069 - loss: 0.1491 - val_accuracy: 0.5405 - val_loss: 0.2215
Epoch 21/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.7862 - loss: 0.1412 - val_accuracy: 0.5405 - val_loss: 0.2303
Epoch 22/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.7379 - loss: 0.1499 - val_accuracy: 0.5405 - val_loss: 0.2270
Epoch 23/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.8138 - loss: 0.1478 - val_accuracy: 0.6216 - val_loss: 0.2185
Epoch 24/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.8069 - loss: 0.1396 - val_accuracy: 0.6216 - val_loss: 0.2169
Epoch 25/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.8000 - loss: 0.1417 - val_accuracy: 0.6216 - val_loss: 0.2190
Epoch 26/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.8414 - loss: 0.1341 - val_accuracy: 0.5676 - val_loss: 0.2208
Epoch 27/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 0.7931 - loss: 0.1349 - val_accuracy: 0.5405 - val_loss: 0.2223
Epoch 28/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.8276 - loss: 0.1451 - val_accuracy: 0.5676 - val_loss: 0.2209
Epoch 29/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.7310 - loss: 0.1474 - val_accuracy: 0.5676 - val_loss: 0.2279
Epoch 30/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.7655 - loss: 0.1434 - val_accuracy: 0.6486 - val_loss: 0.2153
Epoch 31/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.8345 - loss: 0.1328 - val_accuracy: 0.6216 - val_loss: 0.2209
Epoch 32/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.8000 - loss: 0.1357 - val_accuracy: 0.5135 - val_loss: 0.2256
Epoch 33/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 0.8276 - loss: 0.1243 - val_accuracy: 0.5946 - val_loss: 0.2268
Epoch 34/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.8621 - loss: 0.1294 - val_accuracy: 0.5405 - val_loss: 0.2286
Epoch 35/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.7724 - loss: 0.1339 - val_accuracy: 0.5405 - val_loss: 0.2287
Epoch 36/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.7931 - loss: 0.1309 - val_accuracy: 0.6216 - val_loss: 0.2244
Epoch 37/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.8690 - loss: 0.1196 - val_accuracy: 0.5676 - val_loss: 0.2261
Epoch 38/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.7931 - loss: 0.1246 - val_accuracy: 0.5676 - val_loss: 0.2284
Epoch 39/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.8207 - loss: 0.1197 - val_accuracy: 0.6216 - val_loss: 0.2291
Epoch 40/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.8414 - loss: 0.1194 - val_accuracy: 0.5405 - val_loss: 0.2309
Epoch 41/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.8690 - loss: 0.1193 - val_accuracy: 0.6486 - val_loss: 0.2246
Epoch 42/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.8207 - loss: 0.1188 - val_accuracy: 0.6216 - val_loss: 0.2242
Epoch 43/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.8345 - loss: 0.1140 - val_accuracy: 0.6486 - val_loss: 0.2278
Epoch 44/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.8552 - loss: 0.1178 - val_accuracy: 0.5946 - val_loss: 0.2276
Epoch 45/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.7862 - loss: 0.1232 - val_accuracy: 0.5946 - val_loss: 0.2292
Epoch 46/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.8276 - loss: 0.1145 - val_accuracy: 0.6216 - val_loss: 0.2298
Epoch 47/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.8690 - loss: 0.1151 - val_accuracy: 0.5946 - val_loss: 0.2260
Epoch 48/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.8414 - loss: 0.1119 - val_accuracy: 0.5676 - val_loss: 0.2331
Epoch 49/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.8345 - loss: 0.1116 - val_accuracy: 0.5946 - val_loss: 0.2282
Epoch 50/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.8483 - loss: 0.1095 - val_accuracy: 0.6486 - val_loss: 0.2251
Epoch 51/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.8414 - loss: 0.1089 - val_accuracy: 0.6486 - val_loss: 0.2281
Epoch 52/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.8552 - loss: 0.1084 - val_accuracy: 0.6216 - val_loss: 0.2297
Epoch 53/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.8759 - loss: 0.1065 - val_accuracy: 0.5946 - val_loss: 0.2330
Epoch 54/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.8552 - loss: 0.1081 - val_accuracy: 0.5946 - val_loss: 0.2316
Epoch 55/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.8621 - loss: 0.1073 - val_accuracy: 0.6216 - val_loss: 0.2325
Epoch 56/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.8690 - loss: 0.1030 - val_accuracy: 0.5946 - val_loss: 0.2309
Epoch 57/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.8276 - loss: 0.1076 - val_accuracy: 0.6216 - val_loss: 0.2311
Epoch 58/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.8690 - loss: 0.1052 - val_accuracy: 0.6216 - val_loss: 0.2308
Epoch 59/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.8690 - loss: 0.1033 - val_accuracy: 0.5946 - val_loss: 0.2323
Epoch 60/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.8483 - loss: 0.1031 - val_accuracy: 0.5946 - val_loss: 0.2323
Epoch 61/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.8483 - loss: 0.1020 - val_accuracy: 0.6216 - val_loss: 0.2337
Epoch 62/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.8621 - loss: 0.1019 - val_accuracy: 0.5946 - val_loss: 0.2351
Epoch 63/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.8414 - loss: 0.1015 - val_accuracy: 0.6486 - val_loss: 0.2310
Epoch 64/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.8828 - loss: 0.1025 - val_accuracy: 0.6216 - val_loss: 0.2313
Epoch 65/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.8414 - loss: 0.1024 - val_accuracy: 0.6216 - val_loss: 0.2343
Epoch 66/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.8828 - loss: 0.0992 - val_accuracy: 0.6486 - val_loss: 0.2351
Epoch 67/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.8621 - loss: 0.0996 - val_accuracy: 0.6486 - val_loss: 0.2339
Epoch 68/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.8828 - loss: 0.0988 - val_accuracy: 0.6486 - val_loss: 0.2344
Epoch 69/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.8621 - loss: 0.0979 - val_accuracy: 0.6216 - val_loss: 0.2394
Epoch 70/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.8621 - loss: 0.0983 - val_accuracy: 0.6216 - val_loss: 0.2384
Epoch 71/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.8690 - loss: 0.0949 - val_accuracy: 0.5946 - val_loss: 0.2378
Epoch 72/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.8897 - loss: 0.0998 - val_accuracy: 0.6216 - val_loss: 0.2342
Epoch 73/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.8414 - loss: 0.0991 - val_accuracy: 0.6216 - val_loss: 0.2350
Epoch 74/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.8621 - loss: 0.0988 - val_accuracy: 0.6486 - val_loss: 0.2436
Epoch 75/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.8759 - loss: 0.0968 - val_accuracy: 0.6216 - val_loss: 0.2391
Epoch 76/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.8759 - loss: 0.0959 - val_accuracy: 0.6486 - val_loss: 0.2387
Epoch 77/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.8621 - loss: 0.0953 - val_accuracy: 0.6216 - val_loss: 0.2408
Epoch 78/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.8759 - loss: 0.0957 - val_accuracy: 0.6486 - val_loss: 0.2381
Epoch 79/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.8828 - loss: 0.0945 - val_accuracy: 0.6216 - val_loss: 0.2366
Epoch 80/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.8897 - loss: 0.0958 - val_accuracy: 0.6216 - val_loss: 0.2372
Epoch 81/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.8897 - loss: 0.0921 - val_accuracy: 0.6486 - val_loss: 0.2386
Epoch 82/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.8483 - loss: 0.0953 - val_accuracy: 0.5946 - val_loss: 0.2424
Epoch 83/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.8621 - loss: 0.0911 - val_accuracy: 0.6216 - val_loss: 0.2414
Epoch 84/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.8828 - loss: 0.0946 - val_accuracy: 0.6216 - val_loss: 0.2397
Epoch 85/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.8207 - loss: 0.1078 - val_accuracy: 0.6216 - val_loss: 0.2393
Epoch 86/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.8483 - loss: 0.0993 - val_accuracy: 0.6216 - val_loss: 0.2399
Epoch 87/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.8483 - loss: 0.0991 - val_accuracy: 0.6216 - val_loss: 0.2357
Epoch 88/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.8690 - loss: 0.0911 - val_accuracy: 0.5946 - val_loss: 0.2442
Epoch 89/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.8621 - loss: 0.1060 - val_accuracy: 0.6216 - val_loss: 0.2388
Epoch 90/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.8483 - loss: 0.1036 - val_accuracy: 0.6216 - val_loss: 0.2409
Epoch 91/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.8138 - loss: 0.1082 - val_accuracy: 0.6216 - val_loss: 0.2336
Epoch 92/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.8690 - loss: 0.0934 - val_accuracy: 0.5946 - val_loss: 0.2399
Epoch 93/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.8759 - loss: 0.0885 - val_accuracy: 0.5946 - val_loss: 0.2450
Epoch 94/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.8690 - loss: 0.0900 - val_accuracy: 0.6216 - val_loss: 0.2474
Epoch 95/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.8621 - loss: 0.0899 - val_accuracy: 0.6486 - val_loss: 0.2444
Epoch 96/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.8897 - loss: 0.0859 - val_accuracy: 0.6486 - val_loss: 0.2443
Epoch 97/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.8759 - loss: 0.0877 - val_accuracy: 0.6486 - val_loss: 0.2437
Epoch 98/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.8759 - loss: 0.0856 - val_accuracy: 0.6486 - val_loss: 0.2454
Epoch 99/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.8690 - loss: 0.0865 - val_accuracy: 0.6216 - val_loss: 0.2465
Epoch 100/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.8690 - loss: 0.0863 - val_accuracy: 0.6216 - val_loss: 0.2449

Model

In [20]:
data = pd.read_csv("data.csv")
data.head()

,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,sqft_above,sqft_basement,yr_built,yr_renovated,street,city,statezip,country
0,2014-05-02 00:00:00,313000.0,3.0,1.50,1340,7912,1.5,0,0,3,1340,0,1955,2005,18810 Densmore Ave N,Shoreline,WA 98133,USA
1,2014-05-02 00:00:00,2384000.0,5.0,2.50,3650,9050,2.0,0,4,5,3370,280,1921,0,709 W Blaine St,Seattle,WA 98119,USA
2,2014-05-02 00:00:00,342000.0,3.0,2.00,1930,11947,1.0,0,0,4,1930,0,1966,0,26206-26214 143rd Ave SE,Kent,WA 98042,USA
3,2014-05-02 00:00:00,420000.0,3.0,2.25,2000,8030,1.0,0,0,4,1000,1000,1963,0,857 170th Pl NE,Bellevue,WA 98008,USA
4,2014-05-02 00:00:00,550000.0,4.0,2.50,1940,10500,1.0,0,0,4,1140,800,1976,1992,9105 170th Ave NE,Redmond,WA 98052,USA

# model
#### input layerr neuorans 10
#### output layer activation function relu
#### output layer neourans
#### hidden layer number (as you like)
#### activation on the hidden layers
#### nuroans on hidden layers

In [27]:
model  = Sequential()

In [28]:
model.add(Input(shape=(10,)))
model.add(Dense(20 , activation='relu'))
model.add(Dense(1 , 'relu'))
model.compile(optimizer='adam' , loss='mse')
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_5 (Dense)                 │ (None, 20)             │           220 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_6 (Dense)                 │ (None, 1)              │            21 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 241 (964.00 B)

 Trainable params: 241 (964.00 B)

 Non-trainable params: 0 (0.00 B)

In [30]:
y=data[['price']]

In [31]:
x=data[['bedrooms' , 'bathrooms' , 'sqft_living' , 'sqft_lot' , 'floors' , 'waterfront' , 'view' , 'condition' , 'sqft_above' , 'sqft_basement' ]]

In [32]:
x_train , x_test , y_train , y_test = train_test_split(x,y,test_size=0.2 , random_state=42)

In [33]:
model.fit(x_train , y_train ,validation_data = (x_test , y_test), epochs=100 , batch_size=32)

Epoch 1/100

115/115 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 438945447936.0000 - val_loss: 1356735840256.0000
Epoch 2/100
115/115 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 438945480704.0000 - val_loss: 1356735840256.0000
Epoch 3/100
115/115 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 438945546240.0000 - val_loss: 1356735840256.0000
Epoch 4/100
115/115 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 438945480704.0000 - val_loss: 1356735840256.0000
Epoch 5/100
115/115 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 438945611776.0000 - val_loss: 1356735840256.0000
Epoch 6/100
115/115 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 438945644544.0000 - val_loss: 1356735840256.0000
Epoch 7/100
115/115 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 438945579008.0000 - val_loss: 1356735840256.0000
Epoch 8/100
115/115 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 438945611776.0000 - val_loss: 1356735840256.0000
Epoch 9/100
115/115 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 438945546240.0000 - val_loss: 1356735840256.0000
Epoch 10/100
115/115 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 438945480704.0000 - val_loss: 1356735840256.0000
Epoch 11/100
115/115 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 438945415168.0000 - val_loss: 1356735840256.0000
Epoch 12/100
115/115 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 438945349632.0000 - val_loss: 1356735840256.0000
Epoch 13/100
115/115 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 438945447936.0000 - val_loss: 1356735840256.0000
Epoch 14/100
115/115 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 438945579008.0000 - val_loss: 1356735840256.0000
Epoch 15/100
115/115 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 438945710080.0000 - val_loss: 1356735840256.0000
Epoch 16/100
115/115 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 438945513472.0000 - val_loss: 1356735840256.0000
Epoch 17/100
115/115 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 438945513472.0000 - val_loss: 1356735840256.0000
Epoch 18/100
115/115 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 438945480704.0000 - val_loss: 1356735840256.0000
Epoch 19/100
115/115 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 438945579008.0000 - val_loss: 1356735840256.0000
Epoch 20/100
115/115 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 438945644544.0000 - val_loss: 1356735840256.0000
Epoch 21/100
115/115 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 438945546240.0000 - val_loss: 1356735840256.0000
Epoch 22/100
115/115 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 438945611776.0000 - val_loss: 1356735840256.0000
Epoch 23/100
115/115 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 438945579008.0000 - val_loss: 1356735840256.0000
Epoch 24/100
115/115 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 438945513472.0000 - val_loss: 1356735840256.0000
Epoch 25/100
115/115 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 438945579008.0000 - val_loss: 1356735840256.0000
Epoch 26/100
115/115 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 438945546240.0000 - val_loss: 1356735840256.0000
Epoch 27/100
115/115 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 438945513472.0000 - val_loss: 1356735840256.0000
Epoch 28/100
115/115 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 438945579008.0000 - val_loss: 1356735840256.0000
Epoch 29/100
115/115 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 438945513472.0000 - val_loss: 1356735840256.0000
Epoch 30/100
115/115 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 438945480704.0000 - val_loss: 1356735840256.0000
Epoch 31/100
115/115 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 438945480704.0000 - val_loss: 1356735840256.0000
Epoch 32/100
115/115 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 438945579008.0000 - val_loss: 1356735840256.0000
Epoch 33/100
115/115 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 438945579008.0000 - val_loss: 1356735840256.0000
Epoch 34/100
115/115 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 438945480704.0000 - val_loss: 1356735840256.0000
Epoch 35/100
115/115 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 438945611776.0000 - val_loss: 1356735840256.0000
Epoch 36/100
115/115 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 438945480704.0000 - val_loss: 1356735840256.0000
Epoch 37/100
115/115 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 438945579008.0000 - val_loss: 1356735840256.0000
Epoch 38/100
115/115 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 438945415168.0000 - val_loss: 1356735840256.0000
Epoch 39/100
115/115 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 438945480704.0000 - val_loss: 1356735840256.0000
Epoch 40/100
115/115 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 438945480704.0000 - val_loss: 1356735840256.0000
Epoch 41/100
115/115 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 438945546240.0000 - val_loss: 1356735840256.0000
Epoch 42/100
115/115 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 438945546240.0000 - val_loss: 1356735840256.0000
Epoch 43/100
115/115 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 438945480704.0000 - val_loss: 1356735840256.0000
Epoch 44/100
115/115 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 438945480704.0000 - val_loss: 1356735840256.0000
Epoch 45/100
115/115 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 438945513472.0000 - val_loss: 1356735840256.0000
Epoch 46/100
115/115 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 438945546240.0000 - val_loss: 1356735840256.0000
Epoch 47/100
115/115 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 438945480704.0000 - val_loss: 1356735840256.0000
Epoch 48/100
115/115 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 438945415168.0000 - val_loss: 1356735840256.0000
Epoch 49/100
115/115 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 438945579008.0000 - val_loss: 1356735840256.0000
Epoch 50/100
115/115 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 438945447936.0000 - val_loss: 1356735840256.0000
Epoch 51/100
115/115 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 438945480704.0000 - val_loss: 1356735840256.0000
Epoch 52/100
115/115 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 438945546240.0000 - val_loss: 1356735840256.0000
Epoch 53/100
115/115 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 438945513472.0000 - val_loss: 1356735840256.0000
Epoch 54/100
115/115 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 438945480704.0000 - val_loss: 1356735840256.0000
Epoch 55/100
115/115 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 438945480704.0000 - val_loss: 1356735840256.0000
Epoch 56/100
115/115 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 438945480704.0000 - val_loss: 1356735840256.0000
Epoch 57/100
115/115 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 438945546240.0000 - val_loss: 1356735840256.0000
Epoch 58/100
115/115 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 438945513472.0000 - val_loss: 1356735840256.0000
Epoch 59/100
115/115 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 438945447936.0000 - val_loss: 1356735840256.0000
Epoch 60/100
115/115 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 438945644544.0000 - val_loss: 1356735840256.0000
Epoch 61/100
115/115 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 438945644544.0000 - val_loss: 1356735840256.0000
Epoch 62/100
115/115 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 438945415168.0000 - val_loss: 1356735840256.0000
Epoch 63/100
115/115 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 438945546240.0000 - val_loss: 1356735840256.0000
Epoch 64/100
115/115 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 438945447936.0000 - val_loss: 1356735840256.0000
Epoch 65/100
115/115 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 438945579008.0000 - val_loss: 1356735840256.0000
Epoch 66/100
115/115 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 438945546240.0000 - val_loss: 1356735840256.0000
Epoch 67/100
115/115 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 438945710080.0000 - val_loss: 1356735840256.0000
Epoch 68/100
115/115 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 438945480704.0000 - val_loss: 1356735840256.0000
Epoch 69/100
115/115 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 438945546240.0000 - val_loss: 1356735840256.0000
Epoch 70/100
115/115 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 438945546240.0000 - val_loss: 1356735840256.0000
Epoch 71/100
115/115 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 438945579008.0000 - val_loss: 1356735840256.0000
Epoch 72/100
115/115 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 438945579008.0000 - val_loss: 1356735840256.0000
Epoch 73/100
115/115 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 438945611776.0000 - val_loss: 1356735840256.0000
Epoch 74/100
115/115 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 438945415168.0000 - val_loss: 1356735840256.0000
Epoch 75/100
115/115 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 438945579008.0000 - val_loss: 1356735840256.0000
Epoch 76/100
115/115 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 438945611776.0000 - val_loss: 1356735840256.0000
Epoch 77/100
115/115 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 438945447936.0000 - val_loss: 1356735840256.0000
Epoch 78/100
115/115 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 438945513472.0000 - val_loss: 1356735840256.0000
Epoch 79/100
115/115 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 438945513472.0000 - val_loss: 1356735840256.0000
Epoch 80/100
115/115 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 438945579008.0000 - val_loss: 1356735840256.0000
Epoch 81/100
115/115 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 438945415168.0000 - val_loss: 1356735840256.0000
Epoch 82/100
115/115 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 438945611776.0000 - val_loss: 1356735840256.0000
Epoch 83/100
115/115 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 438945480704.0000 - val_loss: 1356735840256.0000
Epoch 84/100
115/115 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 438945644544.0000 - val_loss: 1356735840256.0000
Epoch 85/100
115/115 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 438945513472.0000 - val_loss: 1356735840256.0000
Epoch 86/100
115/115 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 438945513472.0000 - val_loss: 1356735840256.0000
Epoch 87/100
115/115 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 438945579008.0000 - val_loss: 1356735840256.0000
Epoch 88/100
115/115 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 438945480704.0000 - val_loss: 1356735840256.0000
Epoch 89/100
115/115 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 438945644544.0000 - val_loss: 1356735840256.0000
Epoch 90/100
115/115 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 438945644544.0000 - val_loss: 1356735840256.0000
Epoch 91/100
115/115 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 438945579008.0000 - val_loss: 1356735840256.0000
Epoch 92/100
115/115 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 438945447936.0000 - val_loss: 1356735840256.0000
Epoch 93/100
115/115 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 438945579008.0000 - val_loss: 1356735840256.0000
Epoch 94/100
115/115 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 438945513472.0000 - val_loss: 1356735840256.0000
Epoch 95/100
115/115 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 438945611776.0000 - val_loss: 1356735840256.0000
Epoch 96/100
115/115 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 438945546240.0000 - val_loss: 1356735840256.0000
Epoch 97/100
115/115 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 438945546240.0000 - val_loss: 1356735840256.0000
Epoch 98/100
115/115 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 438945644544.0000 - val_loss: 1356735840256.0000
Epoch 99/100
115/115 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 438945447936.0000 - val_loss: 1356735840256.0000
Epoch 100/100
115/115 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 438945480704.0000 - val_loss: 1356735840256.0000